Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\ProgramData\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\ProgramData\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.iloc[1] = ['赵四', 95, 90, 89]  # 修改第 2 行的数据为列表中的值
df
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[29], line 1[0m
[1;32m----> 1[0m df[38;5;241m.[39miloc[[38;5;241m1[39m] [38;5;241m=[39m [[38;5;124m'[39m[38;5;124m赵四[39m[38;5;124m'[39m, [38;5;241m95[39m, [38;5;241m90[39m, [38;5;241m89[39m]  [38;5;66;03m# 修改第 2 行的数据为列表中的值[39;00m
[0;32m      2[0m df

File [1;32mD:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexing.py:818[0m, in [0;36m_LocationIndexer.__setitem__[1;34m(self, key, value)[0m
[0;32m    815[0m [38;5;28mself[39m[38;5;241m.[39m_has_valid_setitem_indexer(key)
[0;32m    817[0m iloc [38;5;241m=[39m [38;5;28mself[39m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mname [38;5;241m==[39m [38;5;124m"[39m[38;5;124miloc[39m[38;5;124m"[39m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39miloc
[1;32m--> 818[0m [43miloc[49m[38;5;241;43m.[39;49m[43m_setitem_with_indexer[49m[43m([49m[43mindexer[49m[43m,[49m[43m [49m[43mvalue[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mname[49m[43m)[49m

File [1;32mD:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexing.py:1795[0m, in [0;36m_iLocIndexer._setitem_with_indexer[1;34m(self, indexer, value, name)[0m
[0;32m   1792[0m [38;5;66;03m# align and set the values[39;00m
[0;32m   1793[0m [38;5;28;01mif[39;00m take_split_path:
[0;32m   1794[0m     [38;5;66;03m# We have to operate column-wise[39;00m
[1;32m-> 1795[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_setitem_with_indexer_split_path[49m[43m([49m[43mindexer[49m[43m,[49m[43m [49m[43mvalue[49m[43m,[49m[43m [49m[43mname[49m[43m)[49m
[0;32m   1796[0m [38;5;28;01melse[39;00m:
[0;32m   1797[0m     [38;5;28mself[39m[38;5;241m.[39m_setitem_single_block(indexer, value, name)

File [1;32mD:\ProgramData\anaconda3\lib\site-packages\pandas\core\indexing.py:1879[0m, in [0;36m_iLocIndexer._setitem_with_indexer_split_path[1;34m(self, indexer, value, name)[0m
[0;32m   1876[0m         [38;5;28mself[39m[38;5;241m.[39m_setitem_single_column(ilocs[[38;5;241m0[39m], value, pi)
[0;32m   1878[0m     [38;5;28;01melse[39;00m:
[1;32m-> 1879[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m   1880[0m             [38;5;124m"[39m[38;5;124mMust have equal len keys and value [39m[38;5;124m"[39m
[0;32m   1881[0m             [38;5;124m"[39m[38;5;124mwhen setting with an iterable[39m[38;5;124m"[39m
[0;32m   1882[0m         )
[0;32m   1884[0m [38;5;28;01melse[39;00m:
[0;32m   1885[0m 
[0;32m   1886[0m     [38;5;66;03m# scalar value[39;00m
[0;32m   1887[0m     [38;5;28;01mfor[39;00m loc [38;5;129;01min[39;00m ilocs:

[1;31mValueError[0m: Must have equal len keys and value when setting with an iterable
ValueError: Must have equal len keys and value when setting with an iterable

